name             "lamp"
maintainer       "Dang Mai"
maintainer_email "contact@dangmai.net"
license          "MIT"
description      "Installs/Configures a LAMP stack with PHP-FPM and APC"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.3"

depends "apt"
depends "apache2"
depends "database"
depends "dotdeb"
depends "jolicode-php"
depends "mysql"
depends "vsftpd"